version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - aszili
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    assignees:
      - aszili
    ignore:
      - dependency-name: golang